config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :artistes
  resources :concerts, only: [:show, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"

  root to: "concerts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artiste.rb
class Artiste < ApplicationRecord
    has_many :concerts
    
    validates :pseudo, presence: true
    validates :age, presence: true
    
    validates :photo, presence: true
    has_attachment :photo, accept: [:jpg, :png, :jpeg]
end

app/models/concert.rb
class Concert < ApplicationRecord
    belongs_to :artiste
    
    validates :salle, presence: true
    validates :date, presence: true
    
    validates :photo, presence: true
    has_attachment :photo, accept: [:jpg, :png, :jpeg]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      # permet de configurer username et avatar à l'inscription
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

      # autorise la modification de ces champs dans le form Devise
      devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
end

app/controllers/artistes_controller.rb
class ArtistesController < ApplicationController
    def show
        @artiste = Artiste.find(params[:id])
    end   
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
    def index
        @concerts = Concert.all
    end
    
    def show
        @concert = Concert.find(params[:id])
    end
    
    def new
        @concert = Concert.new
    end
    
    def create
        @concert = Concert.new(concert_params)
        
        if @concert.valid?
            @concert.save!
            redirect_to root_path
        else
            # réaffiche le template new pour avoir formulaire + erreurs
            render :new
        end
    end

    private

    def concert_params
      # n'autorise que ces paramètres
      params.require(:concert).permit(:artiste, :salle, :date, :description, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artistes_helper.rb
module ArtistesHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/artistes/show.html.erb
<div class="concerts">
  <h1><%= @artiste.pseudo %></h1>

  <%= render partial: "concerts/button_new" %>

  <section class="row concert">
    <div class="col-sm-4">
      <%= cl_image_tag(@artiste.photo.path, width: 500, height: 250, crop: :fill, class: "picture") %>
    </div>
    <div class="col-sm-8">
      <p>Age: <%= @artiste.age %></p>
      <p>Description: <%= @artiste.description %></p>
    </div>
  </section>
</div>

app/views/concerts/_button_list.html.erb
<p class="text-right">
  <%= link_to(root_path, class: "btn btn-default") do %>
    <%= icon("list") %> Liste des Concerts
  <% end %>
</p>

app/views/concerts/_button_new.html.erb
<p class="text-right">
  <%= link_to(new_concert_path, class: "btn btn-default") do %>
    <%= icon("list") %> Nouveau Concert
  <% end %>
</p>

app/views/concerts/_form.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <%= simple_form_for(concert) do |f| %>
      <%= f.input :salle %>
      <%= f.input :style %>
      <%= f.input :date %>
      <%= f.input :description %>
      <%= f.input :photo, as: :attachinary, accept: "image" %>
      <%= f.button :submit, value: t(".submit") %>
    <% end %>
  </div>
</div>

app/views/concerts/index.html.erb
<div class="concerts">
    <h1>Nos Concerts Sur Aix en Provence</h1>

    <%- @concerts.each do |concert| -%>
      <section class="row concert">
          <div class="col-sm-12">
            <h2><%= concert.salle %></h2>
          </div>
          <div class="col-sm-12">
            <%= cl_image_tag(concert.photo.path, width: 300, height: 200, crop: :fill, class: "picture") %>
            <p><%= link_to("Détail sur le concert.", concert_path(concert))%></p>
          </div>
      </section>
    <% end %>
</div>

app/views/concerts/new.html.erb
<div class="concert">
  <h1><%= t("concerts.form.title") %></h1>

  <%= render partial: "concerts/form", locals: { concert: @concert } %>
</div>

app/views/concerts/show.html.erb
<div class="concerts">
  <h1><%= @concert.artiste.pseudo %></h1>

  <%= render partial: "concerts/button_list" %>

  <section class="row concert">
    <div class="col-sm-12">
      <%= cl_image_tag(@concert.photo.path, width: 800, height: 600, crop: :fill, class: "picture") %>
    </div>
    <div class="col-sm-8">
      <p>Artiste: <%= link_to(@concert.artiste.pseudo, artiste_path(@concert.artiste)) %></p>     
      <p>Salle: <%= @concert.salle %></p>     
      <p>Date: <%= @concert.date %></p>
      <p>Description: <%= @concert.description %></p>
    </div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConcertsAixEnProvence</title>
    <%= csrf_meta_tags %>
      
    <meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
        <%= render partial: "shared/flashes" %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb

<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Les Concerts sur Aix en Provence", root_path, class: "navbar-brand") %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="#">Bienvenue, <%= current_user.username %></a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false">
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to edit_user_registration_path do %>
                  <i class="fa fa-user"></i> Modifier le profil
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i> Déconnexion
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to("Connexion", new_user_session_path) %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>